// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace RecommendationML.Model
{
    public class ModelInput
    {
        [ColumnName("userid"), LoadColumn(0)]
        public float Userid { get; set; }


        [ColumnName("musicid"), LoadColumn(1)]
        public float Musicid { get; set; }


        [ColumnName("rating"), LoadColumn(2)]
        public float Rating { get; set; }


    }
}
