// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Linq;
using RecommendationML.Model;

namespace RecommendationML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            TinyRestServerCSharp.TinyRest.Server()
           .WithHttp()
           .WithPort(8080)
           .WithBasePath("/ml")
           .OnGetPath("/", (request, response) => Predict(request, response))
           .Create()
           .Listen();

            Console.Read();
        }

        private static object Predict(Http.IHttpRequest request, Http.IHttpResponse response)
        {
            var idUsr = float.Parse(request.QueryString.Where(x => x.Key == "idUsr").Select(x => x.Value).FirstOrDefault());
            var idSound = float.Parse(request.QueryString.Where(x => x.Key == "idSound").Select(x => x.Value).FirstOrDefault());

            ModelInput sampleData = new ModelInput()
            {
                Userid = idUsr,
                Musicid = idSound,
            };

            var predictionResult = ConsumeModel.Predict(sampleData);

            return predictionResult.Score.ToString("#.#######", new System.Globalization.CultureInfo("en"));
        }
    }
}
